### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by Zuko** [zuhito/node-red-contrib-rocketchat#5]
Hi
I cannot send any messages to Rocket.Chat

`Errors processing request: Request failed with status code 400`

![image](https://user-images.githubusercontent.com/521035/74873556-b7de0200-535f-11ea-8f28-16cb8cfa54f0.png)

**Comment by Zuko** [comment]
Ok, got it, I can't send a message to "private" room. Can you add that option?

**Comment by DevTown** [comment]
Got same error on Public room. Add roomname in field and only got error 400. 
The In Node works (Get MSG with RID and USR) .

**Comment by silveirado** [comment]
Hi @Zuko, I've fixed this into PR #7. If this issue persists for you, let me know.

**Comment by naimo84** [comment]
Hey @silveirado, 

for me it's working with v1.0.4, but not with 1.0.5 ;)
I've downgraded manually an now it's working again .

kind regards,
Benjamin

**Comment by silveirado** [comment]
> Hey @silveirado,
> 
> for me it's working with v1.0.4, but not with 1.0.5 ;)
> I've downgraded manually an now it's working again .
> 
> kind regards,
> Benjamin

Hi @naimo84, can you post more details of your issue? RC version, payload options, server logs,...
